### PR TITLE
Use a unique text-domain, wporg-5ftf

### LINKED ISSUE #25: Pick a textdomain
I see `wporg-5ftf`, `wporg`, `wordpressorg`… Which should we be using for this project?

### PR DESCRIPTION
**Pull request by audrasjb**
Hi,

In this PR, let's edit the various text-domains used on 5ftf theme and plugins.
For reference: https://github.com/WordPress/five-for-the-future/issues/25#issuecomment-551979838 
Fixes #25

### CODE REVIEW

**Review by ryelle — CHANGES_REQUESTED** [review]
Thanks for fixing these (too 🙂 )

Can you also update [the rule in `phpcs.xml.dist`](https://github.com/WordPress/five-for-the-future/blob/aec40e6c7e4c6333dbbf713819ae67d6658c35a9/phpcs.xml.dist#L146)? Once you do that, you'll see there are still 3 files with issues:

- `plugins/wporg-5ftf/includes/pledge-form.php`
- `themes/wporg-5ftf/template-parts/content-5ftf_pledge.php`
- `themes/wporg-5ftf/single-5ftf_pledge.php`

If you can fix those, I'll merge this PR 👍  (I'm also happy to take over, just let me know)

**Comment by audrasjb** [comment]
Thanks @ryelle !
I updated the PR. I don't think I missed anything… but CI checks failed 😬

**Comment by audrasjb** [comment]
Hm, looks like it's because of `type="array"` in:
```
<rule ref="WordPress.WP.I18n">
	<properties>
		<property name="text_domain" type="array" value="wporg-5ftf" />
	</properties>
</rule>
```

**Comment by audrasjb** [comment]
Ok, it's not related to my changes 😊

**Comment by audrasjb** [comment]
Travis is happy now ^^

**Review by ryelle — APPROVED** [review]
looks good now, thanks!

**Pull request merged**
