### PR TITLE
Theme: Single pledge view

### LINKED ISSUE #9: Create the single pledge view
Using the core single view of the Pledge CPT. We can customize the display in the theme templates. It should have the details submitted in the form, and the list of attached contributors.

List Single-d

### PR DESCRIPTION
**Pull request by coreymckrill**
Display a single pledge as shown in #9.

* [x] Create template file
* [x] Output organization details (Pledge title and "About" section)
* [x] Output organization logo
* [x] Output aggregate data about contributor activities from xprofile ("Contributions" section)
* [x] Output list of confirmed contributors ("Contributors" section)
* [x] Style the view
* [x] Determine the URL for the "Report a pledge" link
* [ ] Switch retrieved contributor post statuses from `pending` to `publish`

Fixes #9

### CODE REVIEW

**Comment by ryelle** [comment]
@coreymckrill @iandunn Should we leave the pending visibility to another PR, so that we can test this on wp.org without alerting anyone?

**Comment by iandunn** [comment]
That sounds good to me.

**Comment by ryelle** [comment]
Great - I'm going to merge this since I don't think it needs a full review.

**Comment by iandunn** [comment]
Is there any reason to not `Switch retrieved contributor post statuses from pending to publish` now?

**Comment by coreymckrill** [comment]
Now that we can confirm contributors, I think it's time.

**Comment by iandunn** [comment]
Done in 189c61bfe8bdc3a88b59416254defb00758f7fee

**Comment by ryelle** [comment]
This should also get uncommented if we're confirming contributions - https://github.com/WordPress/five-for-the-future/blob/189c61bfe8bdc3a88b59416254defb00758f7fee/plugins/wporg-5ftf/includes/pledge.php#L196-L199

**Pull request merged**
